// app/layout.tsx
"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./app.css";

// Amplify & UI imports
import { Amplify } from "aws-amplify";
import outputs from "@/amplify_outputs.json";
import "@aws-amplify/ui-react/styles.css";
import { Authenticator } from "@aws-amplify/ui-react";

// your Google font
const inter = Inter({ subsets: ["latin"] });

// keep your metadata export
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// configure Amplify (with SSR for Next)
Amplify.configure({ ...outputs, ssr: true });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* preserve your font class */}
      <body className={inter.className}>
        <Authenticator>
          {({ user, signOut }) => (
            <>
              <header style={{ padding: "1rem", borderBottom: "1px solid #eee" }}>
                <span>Welcome, {user.username}</span>
                <button
                  onClick={signOut}
                  style={{ marginLeft: "1rem", cursor: "pointer" }}
                >
                  Sign Out
                </button>
              </header>
              <main>{children}</main>
            </>
          )}
        </Authenticator>
      </body>
    </html>
  );
}
